yggdrash.node:
  grpc.host: "localhost"
  max-peers: 25

spring.output.ansi.enabled: always
management.endpoint.health.show-details: always
management.health.elasticsearch.enabled: false

---

spring.profiles: validator

spring.main.web-application-type: NONE

---