yggdrash:
  branch:
    default.active: true
  node:
    seed: false
    grpc.host: "localhost"
    grpc.port: 32918
    max-peers: 25
    chain.enabled: true
    chain.gen: false

spring:
  output:
    ansi:
      enabled: always

management:
  endpoint.health.show-details: always
  health:
    diskspace:
      enabled: false
  endpoint:
    restart:
      enabled: true

spring.profiles.active: local

---

spring.profiles: local

logging:
  level:
    io.yggdrash: debug

yggdrash:
  node:
    seed-peer-list:
        "ynode://9ea9225f0b7db3c697c0a2e09cdd65046899058d16f73378c1559d61aa3e10cd5dc9337142728f5a02faadafab2b926e2998d5bc2b62c2183fab75ca996de2ce@localhost:32918"

management.endpoints.web.exposure.include: "*"

---

spring.profiles: dev

logging:
  level:
    io.yggdrash: debug

yggdrash:
  node:
    seed-peer-list:
      - "ynode://9ea9225f0b7db3c697c0a2e09cdd65046899058d16f73378c1559d61aa3e10cd5dc9337142728f5a02faadafab2b926e2998d5bc2b62c2183fab75ca996de2ce@172.16.10.159:32918"

---

spring.profiles: prod

logging:
  level:
    io.yggdrash: info

yggdrash:
  node:
    seed-peer-list:
      - "ynode://9ea9225f0b7db3c697c0a2e09cdd65046899058d16f73378c1559d61aa3e10cd5dc9337142728f5a02faadafab2b926e2998d5bc2b62c2183fab75ca996de2ce@localhost:32918"


---

spring.profiles: bootstrap

yggdrash:
  branch:
    default.active: false
  node:
    seed: true
    chain.enabled: false


---

spring.profiles: master

yggdrash:
  branch:
    default.active: true
  node:
    chain.gen: true
